[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://artwork-generator-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 